### ISSUE TITLE
download video?

### ISSUE THREAD

**Issue by xwhjy** [MorenoLaQuatra/audiocaps-download#1]
Hi! Thanks for sharing this convenient download script. Do you happen to know how to download the company video using ``yt-dlp``?

**Comment by MorenoLaQuatra** [comment]
Do you mean download it beyond the repo itself? I think you just need to use the command line interface 

`yt-dlp https://www.youtube.com/watch?v=VIDEO_ID`

If you want to download it for AudioCaps you need to adapt [this line](https://github.com/MorenoLaQuatra/audiocaps-download/blob/dbe83b56ef97fc82143e78d99614ec30cb0135e7/audiocaps_download/Downloader.py#L295) according to your need.

**Comment by xwhjy** [comment]
> this line

Yes! I need to download the video of each AudioCaps audio but I'm not sure how to only download the 10s clip by specifying the starting and ending seconds.

**Comment by MorenoLaQuatra** [comment]
You can use the same syntax I used in that line to specify the start-end.

`yt-dlp https://www.youtube.com/watch?v=VIDEO_ID --postprocessor-args "-ss 1 -to 11"`

for example, to download from second 1 to second 11
