### ISSUE TITLE
fatal python error: init_sys_streams: can't initialize sys standard streams

### ISSUE THREAD

**Issue by louislau1129** [MorenoLaQuatra/audiocaps-download#4]
When I use `n_jobs> 1`, it shows: 
using backend locybackend with `n_job` concurrent workers.
fatal python error: init_sys_streams: can't initilalize sys standard streams, 
[OS Error] bad file descriptor. 

When n_jobs=1, everthing is ok. But I would like to download faster by parallel.
Having tried increase the `ulimit` for allowing the increased open file descriptors. and reduce the verbose level, nothing works.
Any idea to solve this parallel issue? Thanks in advance!

**Comment by MorenoLaQuatra** [comment]
Hi, I think it may be an OS-specific problem, on which OS are you running this? Also you can try to change the backend if needed: [here](https://github.com/MorenoLaQuatra/audiocaps-download/blob/5b7a56362ee80444546f6b3a4aca1fc83117069d/audiocaps_download/Downloader.py#L91) you can change the backend adding a parameter `backend='multiprocessing'` for example [reference](https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html).

Of course if it works, it should be done also for validation and test sets.

Hope this helps.
